stages:
  test-dvclive:
    cmd: python train.py
    deps:
      - train.py
    params:
      - epochs
    plots:
      - dvclive/plots:
          cache: false
    metrics:
      - dvclive/metrics.json:
          cache: false
